name: weathy
description: A new Flutter application.

version: 1.3.0+1

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.2
    location: ^4.2.1
    get: ^4.1.4
    http:
    flutter_spinkit: ^5.0.0

dev_dependencies:
    flutter_native_splash: ^1.1.8+4
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - images/

    fonts:
        - family: Spartan MB
          fonts:
              - asset: fonts/SpartanMB-Black.otf
                weight: 900

flutter_native_splash:
    color: "#042A49"
    image: images/iconSplash.png
    android: true
    fullscreen: true
